=== mostman47/CS157B-WebServiceProject/new/WebServiceServer/airport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TableAirport">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AirportCode"/>
				<xs:element ref="CityOrAirportName"/>
				<xs:element ref="Country"/>
				<xs:element ref="CountryAbbrviation"/>
				<xs:element ref="CountryCode"/>
				<xs:element ref="GMTOffset"/>
				<xs:element ref="RunwayLengthFeet"/>
				<xs:element ref="RunwayElevationFeet"/>
				<xs:element ref="LatitudeDegree"/>
				<xs:element ref="LatitudeMinute"/>
				<xs:element ref="LatitudeSecond"/>
				<xs:element ref="LatitudeNpeerS"/>
				<xs:element ref="LongitudeDegree"/>
				<xs:element ref="LongitudeMinute"/>
				<xs:element ref="LongitudeSeconds"/>
				<xs:element ref="LongitudeEperW"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RunwayLengthFeet">
		
	</xs:element>
	<xs:element name="RunwayElevationFeet">
		
	</xs:element>
	<xs:element name="LongitudeSeconds">
		
	</xs:element>
	<xs:element name="LongitudeMinute">
		
	</xs:element>
	<xs:element name="LongitudeEperW">
		
	</xs:element>
	<xs:element name="LongitudeDegree">
		
	</xs:element>
	<xs:element name="LatitudeSecond">
		
	</xs:element>
	<xs:element name="LatitudeNpeerS">
	
	</xs:element>
	<xs:element name="LatitudeMinute">
		
	</xs:element>
	<xs:element name="LatitudeDegree">
		
	</xs:element>
	<xs:element name="GMTOffset">
		
	</xs:element>
	<xs:element name="CountryCode">
		
	</xs:element>
	<xs:element name="CountryAbbrviation">
		
	</xs:element>
	<xs:element name="Country">
		
	</xs:element>
	<xs:element name="CityOrAirportName">
		
	</xs:element>
	<xs:element name="AirportCode">
		
	</xs:element>
	<xs:element name="Airport">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TableAirport" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mostman47/CS157B-WebServiceProject/new/Client/airport.xml
<?xml version="1.0" encoding="UTF-8"?>
<Airport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="airport.xsd">
  <TableAirport>
    <AirportCode>TKJ</AirportCode>
    <CityOrAirportName>TOK</CityOrAirportName>
    <Country>United States</Country>
    <CountryAbbrviation>US</CountryAbbrviation>
    <CountryCode>1</CountryCode>
    <GMTOffset>-9</GMTOffset>
    <RunwayLengthFeet>1700</RunwayLengthFeet>
    <RunwayElevationFeet>1670</RunwayElevationFeet>
    <LatitudeDegree>63</LatitudeDegree>
    <LatitudeMinute>18</LatitudeMinute>
    <LatitudeSecond>0</LatitudeSecond>
    <LatitudeNpeerS>N</LatitudeNpeerS>
    <LongitudeDegree>143</LongitudeDegree>
    <LongitudeMinute>0</LongitudeMinute>
    <LongitudeSeconds>0</LongitudeSeconds>
    <LongitudeEperW>W</LongitudeEperW>
  </TableAirport>
  <TableAirport>
    <AirportCode>TKJ</AirportCode>
    <CityOrAirportName>TOK</CityOrAirportName>
    <Country>United States</Country>
    <CountryAbbrviation>US</CountryAbbrviation>
    <CountryCode>1</CountryCode>
    <GMTOffset>-9</GMTOffset>
    <RunwayLengthFeet>1700</RunwayLengthFeet>
    <RunwayElevationFeet>1670</RunwayElevationFeet>
    <LatitudeDegree>63</LatitudeDegree>
    <LatitudeMinute>18</LatitudeMinute>
    <LatitudeSecond>0</LatitudeSecond>
    <LatitudeNpeerS>N</LatitudeNpeerS>
    <LongitudeDegree>143</LongitudeDegree>
    <LongitudeMinute>0</LongitudeMinute>
    <LongitudeSeconds>0</LongitudeSeconds>
    <LongitudeEperW>W</LongitudeEperW>
  </TableAirport>
</Airport>

=== mostman47/CS157B-WebServiceProject/new/WebServiceServer/airport.xml
<?xml version="1.0" encoding="UTF-8"?>
<Airport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="airport.xsd">
	<TableAirport>
		<AirportCode>SJC</AirportCode>
		<CityOrAirportName>SAN JOSE</CityOrAirportName>
		<Country>United States</Country>
		<CountryAbbrviation>US</CountryAbbrviation>
		<CountryCode>91</CountryCode>
		<GMTOffset>8</GMTOffset>
		<RunwayLengthFeet>8899</RunwayLengthFeet>
		<RunwayElevationFeet>56</RunwayElevationFeet>
		<LatitudeDegree>37</LatitudeDegree>
		<LatitudeMinute>21</LatitudeMinute>
		<LatitudeSecond>10</LatitudeSecond>
		<LatitudeNpeerS>N</LatitudeNpeerS>
		<LongitudeDegree>121</LongitudeDegree>
		<LongitudeMinute>55</LongitudeMinute>
		<LongitudeSeconds>10</LongitudeSeconds>
		<LongitudeEperW>W</LongitudeEperW>
	</TableAirport>
	<TableAirport>
		<AirportCode>SJC</AirportCode>
		<CityOrAirportName>SAN JOSE</CityOrAirportName>
		<Country>United States</Country>
		<CountryAbbrviation>US</CountryAbbrviation>
		<CountryCode>91</CountryCode>
		<GMTOffset>8</GMTOffset>
		<RunwayLengthFeet>8899</RunwayLengthFeet>
		<RunwayElevationFeet>56</RunwayElevationFeet>
		<LatitudeDegree>37</LatitudeDegree>
		<LatitudeMinute>21</LatitudeMinute>
		<LatitudeSecond>10</LatitudeSecond>
		<LatitudeNpeerS>N</LatitudeNpeerS>
		<LongitudeDegree>121</LongitudeDegree>
		<LongitudeMinute>55</LongitudeMinute>
		<LongitudeSeconds>10</LongitudeSeconds>
		<LongitudeEperW>W</LongitudeEperW>
	</TableAirport>
	<TableAirport>
		<AirportCode>SJS</AirportCode>
		<CityOrAirportName>SAN JOSE</CityOrAirportName>
		<Country>Bolivia</Country>
		<CountryAbbrviation>BO</CountryAbbrviation>
		<CountryCode>312</CountryCode>
		<GMTOffset>4</GMTOffset>
		<RunwayLengthFeet>3936</RunwayLengthFeet>
		<RunwayElevationFeet>974</RunwayElevationFeet>
		<LatitudeDegree>17</LatitudeDegree>
		<LatitudeMinute>49</LatitudeMinute>
		<LatitudeSecond>0</LatitudeSecond>
		<LatitudeNpeerS>S</LatitudeNpeerS>
		<LongitudeDegree>60</LongitudeDegree>
		<LongitudeMinute>45</LongitudeMinute>
		<LongitudeSeconds>0</LongitudeSeconds>
		<LongitudeEperW>W</LongitudeEperW>
	</TableAirport>
	<TableAirport>
		<AirportCode>SJS</AirportCode>
		<CityOrAirportName>SAN JOSE</CityOrAirportName>
		<Country>Bolivia</Country>
		<CountryAbbrviation>BO</CountryAbbrviation>
		<CountryCode>312</CountryCode>
		<GMTOffset>4</GMTOffset>
		<RunwayLengthFeet>3936</RunwayLengthFeet>
		<RunwayElevationFeet>974</RunwayElevationFeet>
		<LatitudeDegree>17</LatitudeDegree>
		<LatitudeMinute>49</LatitudeMinute>
		<LatitudeSecond>0</LatitudeSecond>
		<LatitudeNpeerS>S</LatitudeNpeerS>
		<LongitudeDegree>60</LongitudeDegree>
		<LongitudeMinute>45</LongitudeMinute>
		<LongitudeSeconds>0</LongitudeSeconds>
		<LongitudeEperW>W</LongitudeEperW>
	</TableAirport>
</Airport>
